name: next_pass
channels:
  - conda-forge
dependencies:
  - asf_search
  - beautifulsoup4
  - geopandas
  - lxml
  - tabulate
  - geopy
  - earthaccess
  - leafmap
  - watermark
  - boto3
  - rasterio
  - xarray 
