name: Distribute to PyPI

on:
  push:
    tags:
      - v*

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and build
        run: |
          git clone https://github.com/${{ github.repository }}.git .
          git checkout ${{ github.ref_name }}

          python3 -m venv /tmp/venv
          . /tmp/venv/bin/activate

          pip install --upgrade pip build twine
          python -m build

          export TWINE_USERNAME=__token__
          export TWINE_PASSWORD=${{ secrets.PYPI_API_TOKEN }}
          python -m twine upload dist/*
        shell: bash
